
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /config
      - type: disk_use_percent
        arg: /backup
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_temperature
      - type: last_boot
